language: php

php:
  - 5.3
  - 5.4

env:
  - DB=sqlite

services:
  - redis-server

before_script:
  - composer install --no-interaction --quiet

script: php tests/lint.php libs/Kdyby/ tests/Kdyby/ && phpunit --verbose
