language: php

php:
  - 5.3
  - 5.4

env:
  - DB=sqlite

services:
  - redis-server

before_script:
  - "sh -c 'curl -s http://getcomposer.org/installer | php'"
  - "sh -c 'php composer.phar install --no-interaction --quiet'"

script: php tests/lint.php libs/Kdyby/ tests/Kdyby/ && phpunit --verbose
