language: php

php:
  - 5.3.3
  - 5.4

before_script:
  - composer install --no-interaction --quiet --dev

script: php tests/lint.php src/Kdyby/ tests/KdybyTests/ && VERBOSE=true ./tests/run-tests.sh -s tests/KdybyTests/
