{block #branch}
<ul{attr class($classes)}>
{foreach $tree as $branch}
{if is_array($branch)}
	{include #branch, 'tree' => $branch, 'classes' => NULL}</li>
{else}
	{if !$iterator->isFirst()}</li>{/if}
	{if !isset($branch->classes)}{? $branch->classes = array(); }{/if}
	<li n:class="isset($branch->listclass) ? $branch->listclass">
		<a href="{$branch->link}" n:tag-if="isset($branch->link)" n:class="isset($branch->class) ? $branch->class">
			<span>{if $branch->title instanceof Html}{!$branch->title}{else}{$branch->title}{/if}</span></a>
	{if $iterator->isLast()}</li>{/if}
{/if}
{/foreach}
</ul>
{/block}